### ISSUE TITLE
Where can I find test_results.csv which is opened in Parameter_Tuning_XGBoost_with_Example/XGBoost models.ipynb?

### ISSUE THREAD

**Issue by yzj19870824** [aarshayj/Analytics_Vidhya#3]
test_results = pd.read_csv('test_results.csv')

**Comment by qzfnihao** [comment]
I found the same question
No test_result.csv,  can not calc Test AUC

**Comment by transposition** [comment]
where is the test_results.csv!!

**Comment by thismlguy** [comment]
I'm sorry that file is not public. You can always divide the the training data into a test and train then run your experiments. Hope that helps.
